// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6WdEF62ar9xBiIfC9d91GKc70dF6V1Us',
    appId: '1:101180242936:web:f52f5bb7be85a2cb91b40d',
    messagingSenderId: '101180242936',
    projectId: 'car-parking-2ae16',
    authDomain: 'car-parking-2ae16.firebaseapp.com',
    storageBucket: 'car-parking-2ae16.firebasestorage.app',
    measurementId: 'G-K6BFCYG9WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_BhxNkxC6ZMAnTHCfnU1qYIeWhVf8SKs',
    appId: '1:101180242936:android:8b3fa54071cf0a4391b40d',
    messagingSenderId: '101180242936',
    projectId: 'car-parking-2ae16',
    storageBucket: 'car-parking-2ae16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb9XcD1j3whDouv2qMSBq0uMwXnWW6_mQ',
    appId: '1:101180242936:ios:8ec033ca604f5d3891b40d',
    messagingSenderId: '101180242936',
    projectId: 'car-parking-2ae16',
    storageBucket: 'car-parking-2ae16.firebasestorage.app',
    iosBundleId: 'com.example.smartCarParking',
  );
}
